name: Deploy to Github Pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                  #fetch-depth: 0
                    submodules: 'recursive'
            - name: Cache Hugo resources
              uses: actions/cache@v4
              env:
                  cache-name: cache-hugo-resources
              with:
                  path: resources
                  key: ${{ env.cache-name }}

            - uses: actions/setup-go@v5
              with:
                  go-version: "^1.17.0"
            - run: go version

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build
              run: hugo --minify --gc

            - name: Build And Deploy
                  id: builddeploy
                  uses: Azure/static-web-apps-deploy@v1
                  with:
                    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_MUSHROOM_0C73DDD1E }}
                    repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                    action: "upload"
                    ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                    # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                    app_location: "/" # App source code path
                    api_location: "api" # Api source code path - optional
                    output_location: "public" # Built app content directory - optional
                    ###### End of Repository/Build Configurations ######
